global:
  scrape_timeout: "5s"
  evaluation_interval: "10s"

scrape_configs:
  - job_name: "go-api"
    static_configs:
      - targets: ["host.docker.internal:8000"]
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    scheme: http
    follow_redirects: true
    body_size_limit: "0"
    sample_limit: 0
    label_limit: 0
    label_name_length_limit: 0
    label_value_length_limit: 0
    target_limit: 0
